### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by orisano** [oreilly-japan/practical-go-programming#10]
ページ番号：24
セクション番号：1.8.1
内容タイトル：スライスのメモリ確保を高速化する
誤っている内容：apeend()
正しい内容：append()
その他コメント：

**Comment by orj-takizawa** [comment]
こちらにて対応済です。ご確認いただけましたら幸いです。

https://github.com/oreilly-japan/practical-go-programming/wiki/Eratta_1e_rev1#p24-181-%E6%9C%AC%E6%96%87%E4%B8%8B%E3%81%8B%E3%82%896%E8%A1%8C%E7%9B%AE
