### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by moutend** [oreilly-japan/practical-go-programming#15]
タイポを見つけたので報告します。

※Issue作成前にオライリージャパンから最新のepub版をダウンロードして確認しました。

## 1.4.3 Goのエラーハンドリング

脱字がありました。

- （誤） 多値を返すことできます。
- （正） 多値を返すことができます。

## 2.3.1 スライスへの型定義

メソッド定義のシンタックスが間違っていました。

- （誤） `type (...)`
- （正） `func (...)`

修正後のGoコードは以下のとおりです。（typeをfuncに置き換えただけです）

```go
// メソッドチェーンにした関数をさらにモデルに押し込む
func (c Consumers) RequiredFollows() Consumers {
	return c.activeConsumer().expires(time.Now().AddDate(0, 1, 0)).sortByExpiredAt()
}

// 可能であればExportしていた関数をプライベート化
func (c Consumers) activeConsumer() Consumers {
	// 契約が有効なユーザーに絞り込みます
}

func (c Consumers) expires(end time.Time) Consumers {
	// endの日時以降に契約が失効するユーザーに絞り込みます
}

func (c Consumers) sortByExpiredAt() Consumers {
	// 契約期限日で昇順ソートします
}
```

## 16.1.2 チャネル

脱字がありました。

- （誤） 言語のコアに組み込まれおり
- （正） 言語のコアに組み込まれており

## epubファイル

本文ではありませんが、epubの中身のxhtmlファイル名にタイポがありました。章のタイトルから察するとチューニングのスペル間違いかと思います。

- （誤） database/turning.xhtml
- （正） database/tuning.xhtml

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。2つ目のものについては #13 と重複しておりますので、そちらにて対応いたします。それ以外については正誤表に記載いたしました。次の増刷時に紙面にも反映させていただきます。

**Comment by moutend** [comment]
投稿する前に軽く調べたのですが、重複を見落としていたようです。失礼しました。

その他については正誤表に追加したこと承知しました。ご連絡ありがとうございました。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
