### ISSUE TITLE
正誤の指摘: 「型と変数で別々に名前空間が存在」

### ISSUE THREAD

**Issue by NagayamaRyoga** [oreilly-japan/practical-go-programming#16]
ページ番号：p36 (初版一刷)
セクション番号：2.1.1
内容タイトル：Goにおける型の定義
誤っている内容：型と変数で別々に名前空間が存在するため、型と変数は出会うことはなく、すれ違い続けます。同じ関数スコープの中でも変数とは名前が衝突しません。
正しい内容：型と変数は同一の名前空間に存在する。
その他コメント：

例として挙げられている、`var int int = 1` はローカル変数`int`が型`int`をシャドーイングしているだけで型と変数が別々の名前空間に存在しているわけではありません。

以下の場合型`x`とローカル変数`x`のスコープが異なるためエラーになりません (グローバル変数と同名のローカル変数が存在できるのと同じ)。

```go
type x int

func f() {
	var x x // OK, ローカル変数xはトップレベルの型xを隠す
}
```

対して、型`x`がローカル変数`x`と同一のスコープに存在している場合はエラーになります (同名のローカル変数が同一スコープに存在できないのと同じ)。

```go
func f() {
	type x int
	var x x // エラー: x redeclared in this block
}
```

このことから型と変数は同一の名前空間にあると言えます。

仮に型と変数が異なる名前空間にある場合、`F(0)`の`F`が型か関数(ポインタ)かが曖昧になります。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。著者さんに確認したところ、「ご指摘の通りです、増刷時に修正します」との回答をいただきました。後日正誤表にも掲載させていただきます。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
