### ISSUE TITLE
正誤の指摘: 「Go1.16から導入される短縮表記について」

### ISSUE THREAD

**Issue by kitagry** [oreilly-japan/practical-go-programming#17]
ページ番号：p65
セクション番号：3.5.1
内容タイトル：タグの記法
誤っている内容：Go1.16から導入される短縮表記について
正しい内容：結局は導入されませんでした。
その他コメント：

Go1.16でapproveはされて一度導入までは至ったのですが、結局は導入されませんでした。
理由としては以下のコードの場合に

```go
type User struct {
	Name string `json xml:"other_tag"`
}

func main() {
	var u User
	fmt.Printf("json tag: %q\n", reflect.TypeOf(u).Field(0).Tag.Get("json"))
}
```

Go1.15: ""
Go1.16: "other_tag"

を返すようになります。これはGoの後方互換性の点からrevertを行うという決断に至ったようです。

https://github.com/golang/go/issues/40281#issuecomment-746758247

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。著者さんより以下のコメントを頂戴しました。

> ご指摘ありがとうございます。マージ後の削除まで追いかけられていませんでした。3刷では「Go 1.16から導入される予定だった短縮表記」として解説し、改訂があるのであればそのときに削除しようと思います。
