### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by satoshi-pes** [oreilly-japan/practical-go-programming#18]
ページ番号：P115　（初版第1刷）
セクション番号：6.1
内容タイトル：プロジェクト構成の事前知識
誤っている内容：「また、これまでGoの歴史の中では比較的変動が大きかった要素だったこともから」の最後の「から」が余分かと思います。
正しい内容：「また、これまでGoの歴史の中では比較的変動が大きかった要素だったことも」
その他コメント：

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加して修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
