### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by satoshi-pes** [oreilly-japan/practical-go-programming#19]
ページ番号：P122　（初版第1刷）
セクション番号：6.3
内容タイトル：Goプロジェクトのライフサイクル
誤っている内容：

下記のgitコマンドのオプション「--tag」が正しくは「--tags」かと思います。

    $ git push origin main --tag

正しい内容：

    $ git push origin main --tags

その他コメント：

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に掲載し、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
