### ISSUE TITLE
スライスのサイズが増加する挙動について

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#20]
ページ番号：P25
セクション番号：1.8
内容タイトル：-
誤っている内容：誤りではないのですが、スライスのサイズの増加の仕方が Go1.18 の場合少し違います。
正しい内容：Go 1.18 の場合は 512 までは2倍ずつ増加するのですが、それ以降の挙動が Go1.17 までの挙動と変わっています。

> The built-in function append now uses a slightly different formula when deciding how much to grow a slice when it must allocate a new underlying array. The new formula is less prone to sudden transitions in allocation behavior.
https://go.dev/doc/go1.18#runtime

その他コメント：完全な誤りではないので、注釈に追加するか、書籍の冒頭で Go1.17 までしかサポートしない旨を記述するかしたほうが良いかなと思います。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。以下著者さんよりの回答です。

> ご指摘の通り、1.17の挙動でした。3刷では1.19での数値に更新するとともに、1.19の場合と追記します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
