### ISSUE TITLE
戻り値を受け取る変数名について

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#21]
ページ番号：P42
セクション番号：2.3.1
内容タイトル：-
誤っている内容：`GetConsumers()` の第1戻り値を受け取る変数が `gets` となっているが、この `gets` は複数形の関数のように読み取られてしまい不適切。
正しい内容：`consumers` のほうがより好ましい。
その他コメント：-

**Comment by orj-takizawa** [comment]
ご提案ありがとうございます。次回の増刷時に採用させていただいます。
