### ISSUE TITLE
context.WithValue() に渡すキーについて

### ISSUE THREAD

**Issue by yoshizow** [oreilly-japan/practical-go-programming#22]
ページ番号：391
セクション番号：16.8
内容タイトル：ウェブサービスでセッションの情報を共有する

誤っている内容：
「このような事態を防ぐために、キー専用のユーザー型とインスタンスを作成して、パッケージの変数 として保持しておきます。」
と書いてあるのに、その後のサンプルコードで
```go
var tokenContextKey = struct{}{}
```
としていて、キー専用のユーザー型を利用していないので、サンプルコードのままでは「このような事態を防ぐ」ことができていません。
最小限のサンプルコードを示して、「実運用ではこうすべき」という話を文章で補足したのだと思いますが、ミスリーディングと感じますし、実際混乱してだいぶ悩んでしまいました。

正しい内容：
サンプルコードでも「キー専用のユーザー型とインスタンスを作成」すると良いと思います。
```go
type contextKey struct{}
var tokenContextKey contextKey = struct{}{}
```
その他コメント：
内容の検証について、こちらを参考にしました: [GoのcontextのValueのkeyの型を再考する - Qiita](https://qiita.com/behiron/items/aec3e1a848f789153d86)

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追記し、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
