### ISSUE TITLE
テーブルベーステスト -> Table Driven Test

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#23]
ページ番号：P80
セクション番号：3.9.1
内容タイトル：-
誤っている内容：「テーブルベーステスト」とは一般的に呼ばれていません。
正しい内容：一般的に呼ばれていて、かつ本書に合わせた「Table Driven Test」のほうが良いかなと思います。
その他コメント：-

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。著者さんより以下のご回答をいただきました。お詫びして訂正いたします。また正誤表にも掲載いたしますのでご参照いただけたら幸いです。

> ご指摘の通りです。本書内の他箇所では「Table Driven Test」または「テーブル駆動テスト」と表記しており、ここでは「テーブル駆動テスト」として、3刷で修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
