### ISSUE TITLE
9.2.3トランザクションラッパーのコードについて

### ISSUE THREAD

**Issue by n-kurasawa** [oreilly-japan/practical-go-programming#24]
ページ番号：207 ~ 208
セクション番号：9.2.3
内容タイトル：トランザクションラッパーでトランザクション制御を実装と分離する方法
誤っている内容：
`BeginTx` で生成した `tx` を `UpdateProduct` の `ExecContext` 実行時に使用していないのでロールバックできないのではないかと思います。

正しい内容：
`BeginTx` で生成した `tx` を `UpdateProduct` の `ExecContext` 実行時に使用する。

その他コメント：
該当箇所はこちらです。
https://github.com/oreilly-japan/practical-go-programming/blob/668e2a6c717a795a5d490d7e7ce91bedfcc14739/ch09/transaction/wrapper/main.go#L22

https://github.com/oreilly-japan/practical-go-programming/blob/668e2a6c717a795a5d490d7e7ce91bedfcc14739/ch09/transaction/wrapper/main.go#L35

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追記し、次回の増刷時に修正します。
