### ISSUE TITLE
修正依頼

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#27]
ページ番号：P94
セクション番号：4.3.3
内容タイトル：-
誤っている内容：違う同じメソッド群を持つ別の型
正しい内容：同じメソッド群を持つ別の型
その他コメント：「違う」と「別の」が二重の意味になっています。また、「違う同じ」のように対義的な修飾語が続くと、意味が通じにくくなります。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に掲載し、次回の増刷時に修正いたします

**Comment by orj-takizawa** [comment]
3刷にて修正しました
