### ISSUE TITLE
P.409 リストA-9: `飲み` -> `のみ`

### ISSUE THREAD

**Issue by mai-nakagawa** [oreilly-japan/practical-go-programming#30]
ページ番号：409
セクション番号：A.10.2
内容タイトル：リストA-9: ブランク識別子
誤っている内容：インデックス飲み
正しい内容：インデックスのみ
その他コメント：第1刷です

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に掲載し、次回の増刷時に修正いたします

**Comment by orj-takizawa** [comment]
3刷にて修正しました
