### ISSUE TITLE
用語の出現場所について

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#33]
ページ番号：P116
セクション番号：6.1.2
内容タイトル：-
誤っている内容：Aモジュール、Bモジュール
正しい内容：Aパッケージ、Bパッケージ
その他コメント：
モジュールでも意味は通じるのですが、Goのモジュールの説明が出てくる前にその用語を使うのは不親切かなと思いました。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。仰る通りです。お詫びして訂正いたします。正誤表にも掲載いたします。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
