### ISSUE TITLE
誤植

### ISSUE THREAD

**Issue by azul915** [oreilly-japan/practical-go-programming#35]
ページ番号：p235(初版)
セクション番号：10.2.3
内容タイトル：リクエストのバリデーション

- **go-playground/validator**を使ったバリデーション実装におけるカスタムメッセージの実装箇所

誤っている内容：

```go
switch fe.Field() {
case "Message":
	out = append(out, fmt.Sprintf("Messageは1 ~ 140文字です"))
case "UserName":
	out = append(out, fmt.Sprintf("Messageは1 ~ 15文字です"))
}
```

正しい内容：

```go
switch fe.Field() {
case "Message":
	out = append(out, "Messageは1 ~ 140文字です")
case "UserName":
	out = append(out, "UserNameは1 ~ 15文字です")
}
```

その他コメント：

- fe.Field()が"UserName"のときはUserNameに関するバリデーションルールのメッセージをoutに詰めるべきなので、メッセージが誤っていると思われる
- ハードコードされたstringをappendするだけなので、fmt.Sprintfは不要

**Comment by orj-takizawa** [comment]
ご指摘の通りです。ありがとうございます。次回の増刷時に修正し、正誤表にも掲載いたします。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
