### ISSUE TITLE
日本語をより分かりやすくする

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#36]
ページ番号：P177
セクション番号：8.1.1
内容タイトル：-
誤っている内容：動的に決まるフィールドはjson.RawMessage型としてデコードせずにバイト列のまま保持しておきます。
正しい内容：動的に決まるフィールドはデコードせずにjson.RawMessage型としてバイト列のまま保持しておきます。
その他コメント：元の文章だと「「json.RawMessage型としてデコードする」ということをせずにバイト列のままにしておく」という風に誤ってとらえてしまい、json.RawMessage型がバイト列のdefined typeであることに気付くのに若干戸惑いました。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。次回の増刷時に修正します

**Comment by orj-takizawa** [comment]
3刷にて修正しました
