### ISSUE TITLE
漢字の修正

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#37]
ページ番号：P190, 193
セクション番号：8.3.2, 8.3.4
内容タイトル：-
誤っている内容：人工
正しい内容：人口
その他コメント：-

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に掲載し、次回の増刷時に修正いたします

**Comment by orj-takizawa** [comment]
3刷にて修正しました
