### ISSUE TITLE
記事への参照について

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#39]
ページ番号：P216
セクション番号：9.6.3
内容タイトル：-
誤っている内容：GoとPostgreSQLでCOPY
正しい内容：次の記事
その他コメント：
どこからどこまでが記事のタイトルなのか、ただの注釈なのか分かりにくいので、修正が必要かなと思いました。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。記事であることを明示するために「GoとPostgreSQLでCOPY」とカッコを追加します

**Comment by orj-takizawa** [comment]
3刷にて修正しました
