### ISSUE TITLE
NormalizeFile 関数内で Normalize 関数を呼び出している io.Writer と io.Reader の引数の順番が逆

### ISSUE THREAD

**Issue by ganchiku** [oreilly-japan/practical-go-programming#4]
ページ番号：89
セクション番号： 4-1
内容タイトル：柔軟なコードを書くインタフェースの利用法
誤っている内容：`Normalize(r, w)`
正しい内容：`Normalize(w, r)`
その他コメント：

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加の上、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
