### ISSUE TITLE
ioutilの排除

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#40]
ページ番号：-
セクション番号：-
内容タイトル：-
誤っている内容：ioutil
正しい内容：io, os
その他コメント：ioutilパッケージはGo1.16で使用が非推奨になったため、代わりにio, osパッケージを使いましょう。

**Comment by orj-takizawa** [comment]
著者さんより以下のコメントを頂戴しました。次回の増刷時に修正します

> ご指摘の通り、iotuilの各関数はDeprecatedなので、3刷にて修正します

**Comment by orj-takizawa** [comment]
3刷にて修正しました
