### ISSUE TITLE
グレースフルシャットダウンについて

### ISSUE THREAD

**Issue by cia-rana** [oreilly-japan/practical-go-programming#45]
ページ番号：P252-P253
セクション番号：10.6.2
内容タイトル：-
誤っている内容：-
正しい内容：-
その他コメント：
サンプルコードはグレースフルシャットダウンしていてとても丁寧なのですが、説明なしで使われていて、逆に説明のノイズになるかなと思いました。

**Comment by orj-takizawa** [comment]
ご提案ありがとうございます。次回の改訂時の参考とさせていただきます。
