### ISSUE TITLE
誤植

### ISSUE THREAD

**Issue by tetsuok** [oreilly-japan/practical-go-programming#48]
ページ番号：P7
セクション番号：1.2.4
内容タイトル：定数 `ErrDatabase` の使用例を説明する文で、if文をif分に誤変換している。
誤っている内容：実行時にif分を使って
正しい内容：実行時にif文を使って
その他コメント：

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に掲載し、次回の増刷時に修正いたします

**Comment by orj-takizawa** [comment]
3刷にて修正しました
