### ISSUE TITLE
docker ベースイメージ

### ISSUE THREAD

**Issue by abekoh** [oreilly-japan/practical-go-programming#49]
ページ番号：初版,p.333
セクション番号：13.2.1
内容タイトル：ベースメージの選択
誤っている内容：
表14-2のデプロイ用イメージとして、
`golang:1.x-slim-bullseye` とあるが、このようなタグは存在しない

https://hub.docker.com/_/golang

正しい内容：

`debian:slim-bullseye` の間違い？

その他コメント：

**Comment by shibukawa** [comment]
回答：ご指摘の通り、``debian:slim-bullseye``の間違いでした。

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。著者さんに確認したところ、ご指摘の通りとの回答でした。お詫びして訂正いたします。次回の増刷時に修正し、正誤表にも掲載いたします。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
