### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by mynaoki** [oreilly-japan/practical-go-programming#5]
ページ番号：199, 217
セクション番号：9章
内容タイトル：Go とリレーショナル・データベース
誤っている内容：AWS DynamoDB
正しい内容：Amazon DynamoDB
その他コメント：N/A

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加の上、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
