### ISSUE TITLE
P40

### ISSUE THREAD

**Issue by mynaoki** [oreilly-japan/practical-go-programming#6]
ページ番号：40
セクション番号：2.2.2
内容タイトル：-
誤っている内容：サンプルコードの内容が重複
正しい内容：２つ目のコードは map のインデックスアクセス？
その他コメント：

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。下記正誤表の通りサンプルコードを修正します。次回の増刷時に修正します。

https://github.com/oreilly-japan/practical-go-programming/wiki/Eratta_1e_rev2#p40-222-%E4%B8%8B%E3%81%8B%E3%82%8914%E8%A1%8C%E7%9B%AE%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF

**Comment by orj-takizawa** [comment]
3刷にて修正しました
