### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by parsee1053** [oreilly-japan/practical-go-programming#8]
ページ番号：399
セクション番号：A.1
内容タイトル：Hello World
誤っている内容：実行ファイルでもライブラリでもまずは次のコマンドをたいて
正しい内容：実行ファイルでもライブラリでもまずは次のコマンドを**た**たいて(叩いて？)
その他コメント：P.399の下から7行目

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加の上、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
