### ISSUE TITLE
正誤の指摘

### ISSUE THREAD

**Issue by parsee1053** [oreilly-japan/practical-go-programming#9]
ページ番号：171
セクション番号：8.1.1
内容タイトル：基本的なエンコードとデコード
誤っている内容：encoding/jsonパッケージの内部的な処理では**reflrect**パッケージを**用いていて**おり、
正しい内容：encoding/jsonパッケージの内部的な処理では**reflect**パッケージを**用いて**おり、
その他コメント：P.171の脚注部分

**Comment by orj-takizawa** [comment]
ご指摘ありがとうございます。正誤表に追加の上、次回の増刷時に修正します。

**Comment by orj-takizawa** [comment]
3刷にて修正しました
